
import * as t from 'io-ts';
import {RTTI_Extension} from './RTTI_Extension';
import {RTTI_Element} from './RTTI_Element';
import {RTTI_Coding} from './RTTI_Coding';
import {RTTI_ElementDefinition_Slicing} from './RTTI_ElementDefinition_Slicing';

import {RTTI_ElementDefinition_Base} from './RTTI_ElementDefinition_Base';
import {RTTI_ElementDefinition_Type} from './RTTI_ElementDefinition_Type';
import {RTTI_Address} from './RTTI_Address';
import {RTTI_Age} from './RTTI_Age';
import {RTTI_Annotation} from './RTTI_Annotation';
import {RTTI_Attachment} from './RTTI_Attachment';
import {RTTI_CodeableConcept} from './RTTI_CodeableConcept';
import {RTTI_ContactPoint} from './RTTI_ContactPoint';
import {RTTI_Count} from './RTTI_Count';
import {RTTI_Distance} from './RTTI_Distance';
import {RTTI_Duration} from './RTTI_Duration';
import {RTTI_HumanName} from './RTTI_HumanName';
import {RTTI_Identifier} from './RTTI_Identifier';
import {RTTI_Money} from './RTTI_Money';
import {RTTI_Period} from './RTTI_Period';
import {RTTI_Quantity} from './RTTI_Quantity';
import {RTTI_Range} from './RTTI_Range';
import {RTTI_Ratio} from './RTTI_Ratio';
import {RTTI_Reference} from './RTTI_Reference';
import {RTTI_SampledData} from './RTTI_SampledData';
import {RTTI_Signature} from './RTTI_Signature';
import {RTTI_Timing} from './RTTI_Timing';
import {RTTI_ParameterDefinition} from './RTTI_ParameterDefinition';
import {RTTI_DataRequirement} from './RTTI_DataRequirement';
import {RTTI_RelatedArtifact} from './RTTI_RelatedArtifact';
import {RTTI_ContactDetail} from './RTTI_ContactDetail';
import {RTTI_Contributor} from './RTTI_Contributor';
import {RTTI_TriggerDefinition} from './RTTI_TriggerDefinition';
import {RTTI_Expression} from './RTTI_Expression';
import {RTTI_UsageContext} from './RTTI_UsageContext';
import {RTTI_Dosage} from './RTTI_Dosage';
import {RTTI_ElementDefinition_Example} from './RTTI_ElementDefinition_Example';

import {RTTI_ElementDefinition_Constraint} from './RTTI_ElementDefinition_Constraint';
import {RTTI_ElementDefinition_Binding} from './RTTI_ElementDefinition_Binding';
import {RTTI_ElementDefinition_Mapping} from './RTTI_ElementDefinition_Mapping';

export enum ElementDefinitionRepresentationKind {
                xmlAttr = 'xmlAttr',
xmlText = 'xmlText',
typeAttr = 'typeAttr',
cdaText = 'cdaText',
xhtml = 'xhtml'
            }
const ElementDefinitionRepresentationKindKeys = t.keyof({
                [ElementDefinitionRepresentationKind.xmlAttr]: null,
[ElementDefinitionRepresentationKind.xmlText]: null,
[ElementDefinitionRepresentationKind.typeAttr]: null,
[ElementDefinitionRepresentationKind.cdaText]: null,
[ElementDefinitionRepresentationKind.xhtml]: null
            });


        const mandatory = t.type({
           
        });
        

        const partial = t.partial({
            id: t.string,
extension: t.array(RTTI_Extension),
modifierExtension: t.array(RTTI_Extension),
path: t.string,
_path: RTTI_Element,
representation: t.array(ElementDefinitionRepresentationKindKeys),
_representation: t.array(RTTI_Element),
sliceName: t.string,
_sliceName: RTTI_Element,
sliceIsConstraining: t.boolean,
_sliceIsConstraining: RTTI_Element,
label: t.string,
_label: RTTI_Element,
code: t.array(RTTI_Coding),
slicing: RTTI_ElementDefinition_Slicing,
short: t.string,
_short: RTTI_Element,
definition: t.string,
_definition: RTTI_Element,
comment: t.string,
_comment: RTTI_Element,
requirements: t.string,
_requirements: RTTI_Element,
alias: t.array(t.string),
_alias: t.array(RTTI_Element),
min: t.number,
_min: RTTI_Element,
max: t.string,
_max: RTTI_Element,
base: RTTI_ElementDefinition_Base,
contentReference: t.string,
_contentReference: RTTI_Element,
type: t.array(RTTI_ElementDefinition_Type),
defaultValueBase64Binary: t.string,
_defaultValueBase64Binary: RTTI_Element,
defaultValueBoolean: t.boolean,
_defaultValueBoolean: RTTI_Element,
defaultValueCanonical: t.string,
_defaultValueCanonical: RTTI_Element,
defaultValueCode: t.string,
_defaultValueCode: RTTI_Element,
defaultValueDate: t.string,
_defaultValueDate: RTTI_Element,
defaultValueDateTime: t.string,
_defaultValueDateTime: RTTI_Element,
defaultValueDecimal: t.number,
_defaultValueDecimal: RTTI_Element,
defaultValueId: t.string,
_defaultValueId: RTTI_Element,
defaultValueInstant: t.string,
_defaultValueInstant: RTTI_Element,
defaultValueInteger: t.number,
_defaultValueInteger: RTTI_Element,
defaultValueMarkdown: t.string,
_defaultValueMarkdown: RTTI_Element,
defaultValueOid: t.string,
_defaultValueOid: RTTI_Element,
defaultValuePositiveInt: t.number,
_defaultValuePositiveInt: RTTI_Element,
defaultValueString: t.string,
_defaultValueString: RTTI_Element,
defaultValueTime: t.string,
_defaultValueTime: RTTI_Element,
defaultValueUnsignedInt: t.number,
_defaultValueUnsignedInt: RTTI_Element,
defaultValueUri: t.string,
_defaultValueUri: RTTI_Element,
defaultValueUrl: t.string,
_defaultValueUrl: RTTI_Element,
defaultValueUuid: t.string,
_defaultValueUuid: RTTI_Element,
defaultValueAddress: RTTI_Address,
defaultValueAge: RTTI_Age,
defaultValueAnnotation: RTTI_Annotation,
defaultValueAttachment: RTTI_Attachment,
defaultValueCodeableConcept: RTTI_CodeableConcept,
defaultValueCoding: RTTI_Coding,
defaultValueContactPoint: RTTI_ContactPoint,
defaultValueCount: RTTI_Count,
defaultValueDistance: RTTI_Distance,
defaultValueDuration: RTTI_Duration,
defaultValueHumanName: RTTI_HumanName,
defaultValueIdentifier: RTTI_Identifier,
defaultValueMoney: RTTI_Money,
defaultValuePeriod: RTTI_Period,
defaultValueQuantity: RTTI_Quantity,
defaultValueRange: RTTI_Range,
defaultValueRatio: RTTI_Ratio,
defaultValueReference: RTTI_Reference,
defaultValueSampledData: RTTI_SampledData,
defaultValueSignature: RTTI_Signature,
defaultValueTiming: RTTI_Timing,
defaultValueParameterDefinition: RTTI_ParameterDefinition,
defaultValueDataRequirement: RTTI_DataRequirement,
defaultValueRelatedArtifact: RTTI_RelatedArtifact,
defaultValueContactDetail: RTTI_ContactDetail,
defaultValueContributor: RTTI_Contributor,
defaultValueTriggerDefinition: RTTI_TriggerDefinition,
defaultValueExpression: RTTI_Expression,
defaultValueUsageContext: RTTI_UsageContext,
defaultValueDosage: RTTI_Dosage,
meaningWhenMissing: t.string,
_meaningWhenMissing: RTTI_Element,
orderMeaning: t.string,
_orderMeaning: RTTI_Element,
fixedBase64Binary: t.string,
_fixedBase64Binary: RTTI_Element,
fixedBoolean: t.boolean,
_fixedBoolean: RTTI_Element,
fixedCanonical: t.string,
_fixedCanonical: RTTI_Element,
fixedCode: t.string,
_fixedCode: RTTI_Element,
fixedDate: t.string,
_fixedDate: RTTI_Element,
fixedDateTime: t.string,
_fixedDateTime: RTTI_Element,
fixedDecimal: t.number,
_fixedDecimal: RTTI_Element,
fixedId: t.string,
_fixedId: RTTI_Element,
fixedInstant: t.string,
_fixedInstant: RTTI_Element,
fixedInteger: t.number,
_fixedInteger: RTTI_Element,
fixedMarkdown: t.string,
_fixedMarkdown: RTTI_Element,
fixedOid: t.string,
_fixedOid: RTTI_Element,
fixedPositiveInt: t.number,
_fixedPositiveInt: RTTI_Element,
fixedString: t.string,
_fixedString: RTTI_Element,
fixedTime: t.string,
_fixedTime: RTTI_Element,
fixedUnsignedInt: t.number,
_fixedUnsignedInt: RTTI_Element,
fixedUri: t.string,
_fixedUri: RTTI_Element,
fixedUrl: t.string,
_fixedUrl: RTTI_Element,
fixedUuid: t.string,
_fixedUuid: RTTI_Element,
fixedAddress: RTTI_Address,
fixedAge: RTTI_Age,
fixedAnnotation: RTTI_Annotation,
fixedAttachment: RTTI_Attachment,
fixedCodeableConcept: RTTI_CodeableConcept,
fixedCoding: RTTI_Coding,
fixedContactPoint: RTTI_ContactPoint,
fixedCount: RTTI_Count,
fixedDistance: RTTI_Distance,
fixedDuration: RTTI_Duration,
fixedHumanName: RTTI_HumanName,
fixedIdentifier: RTTI_Identifier,
fixedMoney: RTTI_Money,
fixedPeriod: RTTI_Period,
fixedQuantity: RTTI_Quantity,
fixedRange: RTTI_Range,
fixedRatio: RTTI_Ratio,
fixedReference: RTTI_Reference,
fixedSampledData: RTTI_SampledData,
fixedSignature: RTTI_Signature,
fixedTiming: RTTI_Timing,
fixedParameterDefinition: RTTI_ParameterDefinition,
fixedDataRequirement: RTTI_DataRequirement,
fixedRelatedArtifact: RTTI_RelatedArtifact,
fixedContactDetail: RTTI_ContactDetail,
fixedContributor: RTTI_Contributor,
fixedTriggerDefinition: RTTI_TriggerDefinition,
fixedExpression: RTTI_Expression,
fixedUsageContext: RTTI_UsageContext,
fixedDosage: RTTI_Dosage,
patternBase64Binary: t.string,
_patternBase64Binary: RTTI_Element,
patternBoolean: t.boolean,
_patternBoolean: RTTI_Element,
patternCanonical: t.string,
_patternCanonical: RTTI_Element,
patternCode: t.string,
_patternCode: RTTI_Element,
patternDate: t.string,
_patternDate: RTTI_Element,
patternDateTime: t.string,
_patternDateTime: RTTI_Element,
patternDecimal: t.number,
_patternDecimal: RTTI_Element,
patternId: t.string,
_patternId: RTTI_Element,
patternInstant: t.string,
_patternInstant: RTTI_Element,
patternInteger: t.number,
_patternInteger: RTTI_Element,
patternMarkdown: t.string,
_patternMarkdown: RTTI_Element,
patternOid: t.string,
_patternOid: RTTI_Element,
patternPositiveInt: t.number,
_patternPositiveInt: RTTI_Element,
patternString: t.string,
_patternString: RTTI_Element,
patternTime: t.string,
_patternTime: RTTI_Element,
patternUnsignedInt: t.number,
_patternUnsignedInt: RTTI_Element,
patternUri: t.string,
_patternUri: RTTI_Element,
patternUrl: t.string,
_patternUrl: RTTI_Element,
patternUuid: t.string,
_patternUuid: RTTI_Element,
patternAddress: RTTI_Address,
patternAge: RTTI_Age,
patternAnnotation: RTTI_Annotation,
patternAttachment: RTTI_Attachment,
patternCodeableConcept: RTTI_CodeableConcept,
patternCoding: RTTI_Coding,
patternContactPoint: RTTI_ContactPoint,
patternCount: RTTI_Count,
patternDistance: RTTI_Distance,
patternDuration: RTTI_Duration,
patternHumanName: RTTI_HumanName,
patternIdentifier: RTTI_Identifier,
patternMoney: RTTI_Money,
patternPeriod: RTTI_Period,
patternQuantity: RTTI_Quantity,
patternRange: RTTI_Range,
patternRatio: RTTI_Ratio,
patternReference: RTTI_Reference,
patternSampledData: RTTI_SampledData,
patternSignature: RTTI_Signature,
patternTiming: RTTI_Timing,
patternParameterDefinition: RTTI_ParameterDefinition,
patternDataRequirement: RTTI_DataRequirement,
patternRelatedArtifact: RTTI_RelatedArtifact,
patternContactDetail: RTTI_ContactDetail,
patternContributor: RTTI_Contributor,
patternTriggerDefinition: RTTI_TriggerDefinition,
patternExpression: RTTI_Expression,
patternUsageContext: RTTI_UsageContext,
patternDosage: RTTI_Dosage,
example: t.array(RTTI_ElementDefinition_Example),
minValueDate: t.string,
_minValueDate: RTTI_Element,
minValueDateTime: t.string,
_minValueDateTime: RTTI_Element,
minValueInstant: t.string,
_minValueInstant: RTTI_Element,
minValueTime: t.string,
_minValueTime: RTTI_Element,
minValueDecimal: t.number,
_minValueDecimal: RTTI_Element,
minValueInteger: t.number,
_minValueInteger: RTTI_Element,
minValuePositiveInt: t.number,
_minValuePositiveInt: RTTI_Element,
minValueUnsignedInt: t.number,
_minValueUnsignedInt: RTTI_Element,
minValueQuantity: RTTI_Quantity,
maxValueDate: t.string,
_maxValueDate: RTTI_Element,
maxValueDateTime: t.string,
_maxValueDateTime: RTTI_Element,
maxValueInstant: t.string,
_maxValueInstant: RTTI_Element,
maxValueTime: t.string,
_maxValueTime: RTTI_Element,
maxValueDecimal: t.number,
_maxValueDecimal: RTTI_Element,
maxValueInteger: t.number,
_maxValueInteger: RTTI_Element,
maxValuePositiveInt: t.number,
_maxValuePositiveInt: RTTI_Element,
maxValueUnsignedInt: t.number,
_maxValueUnsignedInt: RTTI_Element,
maxValueQuantity: RTTI_Quantity,
maxLength: t.number,
_maxLength: RTTI_Element,
condition: t.array(t.string),
_condition: t.array(RTTI_Element),
constraint: t.array(RTTI_ElementDefinition_Constraint),
mustSupport: t.boolean,
_mustSupport: RTTI_Element,
isModifier: t.boolean,
_isModifier: RTTI_Element,
isModifierReason: t.string,
_isModifierReason: RTTI_Element,
isSummary: t.boolean,
_isSummary: RTTI_Element,
binding: RTTI_ElementDefinition_Binding,
mapping: t.array(RTTI_ElementDefinition_Mapping)
        });
        

        export var RTTI_ElementDefinition:any = t.intersection([mandatory, partial]);
        

export type IElementDefinition = t.TypeOf<typeof RTTI_ElementDefinition>;
        
        